const authors = [
  { name: 'Hulk Hogan' },
  { name: 'Lil Yachty' },
  { name: 'Roger Goodell' },
  { name: 'John Madden' },
  { name: 'Pauly Shore' },
  { name: 'Keanu Reeves' },
  { name: 'Katy Perry' },
  { name: 'Owen Wilson' },
  { name: 'Jean-Claude Van Damme' },
  { name: 'Derek Jeter' },
  { name: 'Matthew McConaughey' },
  { name: 'Howard Stern, episode 256: "Stripper Secrets"' },
  { name: 'Eddie Van Halen' },
  { name: 'Richard Simmons' },
  { name: 'Coolio' },
  { name: 'Metallica: "Ride the Lightning"' },
  { name: 'Rob Gronkowski' },
  { name: 'Pete Wentz' },
  { name: 'Toto: "Africa"' },
  { name: 'Riff Raff' },
  { name: 'Kevin Federline' },
  { name: 'Will Ferrell in "Elf"' },
  { name: 'Ashton Kutcher' },
  { name: 'Randy "Macho Man" Savage' },
  { name: 'Dwayne "The Rock" Johnson' },
  { name: 'Nick Cage in "Con Air"' },
  { name: 'TGI Friday\'s Employee Handbook, page 14' },
  { name: 'Justin Bieber' },
  { name: 'Adam Sandler in "Billy Madison"' },
  { name: 'Lil B' },
  { name: 'Arnold Schwarzenegger in "Jingle All The Way"' },
  { name: 'Vanilla Ice' },
  { name: 'Michael Jackson in "The Wiz"' },
  { name: 'Judge Dredd' },
];

export default authors;
