const goofy = [
  { name: 'ROGER GOODELL' },
  { name: 'HULK HOGAN' },
  { name: 'LIL YACHTY' },
  { name: 'JOHN MADDEN' },
  { name: 'PAULY SHORE' },
  { name: 'KEANU REEVES' },
  { name: 'KATY PERRY' },
  { name: 'OWEN WILSON' },
  { name: 'JEAN-CLAUDE VAN DAMME' },
  { name: 'DEREK JETER' },
  { name: 'MATTHEW MCCONAUGHEY' },
  { name: 'HOWARD STERN, EPISODE 256: "STRIPPER SECRETS"' },
  { name: 'EDDIE VAN HALEN' },
  { name: 'RICHARD SIMMONS' },
  { name: 'COOLIO' },
  { name: 'METALLICA: "RIDE THE LIGHTNING"' },
  { name: 'ROB GRONKOWSKI' },
  { name: 'PETE WENTZ' },
  { name: 'TOTO: "AFRICA"' },
  { name: 'RIFF RAFF' },
  { name: 'KEVIN FEDERLINE' },
  { name: 'WILL FERRELL IN "ELF"' },
  { name: 'ASHTON KUTCHER IN "THE BUTTERFLY EFFECT"' },
  { name: 'RANDY "MACHO MAN" SAVAGE' },
  { name: 'DWAYNE "THE ROCK" JOHNSON' },
  { name: 'NICK CAGE IN "CON AIR"' },
  { name: 'TGI FRIDAYS EMPLOYEE HANDBOOK, PAGE 14' },
  { name: 'JUSTIN BIEBER' },
  { name: 'ADAM SANDLER IN "BILLY MADISON"' },
  { name: 'GUCCI MANE' },
  { name: 'ARNOLD SCHWARZENEGGER IN "JINGLE ALL THE WAY"' },
  { name: 'JUDGE DREDD' },
  { name: 'TIM "THE TOOL MAN" TAYLOR' },
  { name: 'JADEN SMITH' },
];

const real = [
  { name: 'NOAM CHOMSKY' },
  { name: 'SIGMUND FREUD' },
  { name: 'MICHEL FOUCAULT' },
  { name: 'ROBERT FROST' },
  { name: 'MAYA ANGELOU' },
  { name: 'LANGSTON HUGHES' },
  { name: 'EMILY DICKINSON' },
  { name: 'NELSON MANDELA' },
  { name: 'MAHATMA GANDHI' },
  { name: 'JANE AUSTEN' },
  { name: 'ERNEST HEMINGWAY' },
  { name: 'ALBERT CAMUS' },
  { name: 'ELEANOR ROOSEVELT' },
  { name: 'HENRY DAVID THOREAU' },
  { name: 'WILLIAM SHAKESPEARE' },
  { name: 'KURT VONNEGUT' },
  { name: 'BERTRAND RUSSEL' },
  { name: 'WINSTON CHURCHILL' },
  { name: 'PRINCESS DIANA' },
];

export default { goofy, real };
